version: '3.9'
services:
    next:
        image: ghcr.io/ifly7charlie/ogr-next:latest
        build:
            context: .
            dockerfile: ./conf/Dockerfile
            target: next
        depends_on:
            aprs:
                condition: service_healthy
        environment:
            - NEXT_PUBLIC_SITEURL
            - NEXT_PUBLIC_DATA_URL
            - NEXT_PUBLIC_MAPBOX_ACCESS_TOKEN
            - NEXT_PUBLIC_AIRSPACE_API_KEY
        volumes:
            - arrow:/ognrange/data/arrow:ro
        restart: always
    aprs:
        image: ghcr.io/ifly7charlie/ogr-aprs:latest
        build:
            context: .
            dockerfile: ./conf/Dockerfile
            target: aprs
        command: node dist/bin/aprs.js
        deploy:
            resources:
                limits:
                    cpus: '1'
                    memory: 5000M
        restart: always
        environment:
            - NEXT_PUBLIC_MAPBOX_ACCESS_TOKEN
        volumes:
            - db:/ognrange/data/db
            - arrow:/ognrange/data/arrow
    apache:
        image: ghcr.io/ifly7charlie/ogr-apache:latest
        build:
            context: .
            dockerfile: ./conf/Dockerfile
            target: apache
        restart: always
        tty: true
        stdin_open: true
        volumes:
            - arrow:/ognrange/data/arrow:ro
        depends_on:
            next:
                condition: service_healthy
            aprs:
                condition: service_healthy
        ports:
            - 80:8000
            - 443:8443
volumes:
    arrow:
    db:
